CREATE TABLE `USERS` (
	`ID` int NOT NULL,
	`LOGIN` char(128) NOT NULL UNIQUE,
	`PASS` char(20) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `POSTS` (
	`ID` int NOT NULL,
	`USER_ID` int NOT NULL,
	`TITLE` char(128) NOT NULL,
	`BODY` char(10000) NOT NULL,
	`PUBLDATE` TIMESTAMP NOT NULL,
	`COMENTS` bool NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `COMENTS` (
	`ID` int NOT NULL,
	`USER_ID` int NOT NULL,
	`POST_ID` int NOT NULL,
	`BODY` char(1000) NOT NULL,
	`PUBLDATE` TIMESTAMP NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `POSTS`   ADD CONSTRAINT `POSTS_FK0`   FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `COMENTS` ADD CONSTRAINT `COMENTS_FK0` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`);
ALTER TABLE `COMENTS` ADD CONSTRAINT `COMENTS_FK1` FOREIGN KEY (`POST_ID`) REFERENCES `POSTS`(`ID`);

